import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getPerfilFromSession } from '@/lib/auth-server'
import { generateTempPassword, sendWelcomeEmail } from '@/lib/utils-auth'

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export async function POST(request: Request) {
  try {
    const session = await getPerfilFromSession()
    if (!session || session.perfil.rol !== 'admin') {
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 })
    }

    const body = await request.json()
    const email = typeof body.email === 'string' ? body.email.trim().toLowerCase() : ''
    const nombre = typeof body.nombre === 'string' ? body.nombre.trim() : ''
    const telefono = typeof body.telefono === 'string' ? body.telefono.trim() : ''
    const passwordInput = typeof body.password === 'string' ? body.password.trim() : ''

    if (!email || !nombre) {
      return NextResponse.json(
        { error: 'Email y nombre son requeridos' },
        { status: 400 }
      )
    }

    if (!EMAIL_REGEX.test(email)) {
      return NextResponse.json({ error: 'Email inválido' }, { status: 400 })
    }

    // Si no se envía contraseña, se genera una automática
    const password = passwordInput || generateTempPassword()
    const autoGenerated = !passwordInput

    const admin = createAdminClient()

    const { data: authData, error: authError } =
      await admin.auth.admin.createUser({
        email,
        password,
        email_confirm: true,
        user_metadata: { full_name: nombre },
      })

    if (authError) {
      const dup = /already|registered|exists/i.test(authError.message)
      return NextResponse.json(
        {
          error: dup
            ? 'Ya existe un usuario registrado con ese correo.'
            : authError.message,
        },
        { status: dup ? 409 : 400 }
      )
    }

    const userId = authData.user!.id

    const { error: perfilError } = await admin.from('perfiles').upsert(
      {
        id: userId,
        email,
        nombre_completo: nombre,
        rol: 'profesor',
        matricula: null,
        programa_id: null,
        telefono: telefono || null,
      },
      { onConflict: 'id' }
    )

    if (perfilError) {
      await admin.auth.admin.deleteUser(userId)
      return NextResponse.json({ error: perfilError.message }, { status: 400 })
    }

    const emailResult = await sendWelcomeEmail({
      email,
      nombre,
      tempPassword: password,
      rol: 'profesor',
    })

    return NextResponse.json({
      success: true,
      userId,
      autoGenerated,
      // Mostramos la contraseña una sola vez para que el admin pueda compartirla
      tempPassword: password,
      emailSent: emailResult.sent,
      emailError: emailResult.error ?? null,
    })
  } catch (error) {
    console.error('Create profesor error:', error)
    return NextResponse.json({ error: 'Error al crear profesor' }, { status: 500 })
  }
}

export async function GET() {
  try {
    const session = await getPerfilFromSession()
    if (!session || session.perfil.rol !== 'admin') {
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 })
    }

    const admin = createAdminClient()
    const { data, error } = await admin
      .from('perfiles')
      .select('*')
      .eq('rol', 'profesor')
      .order('nombre_completo')

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 })
    }

    return NextResponse.json({ profesores: data })
  } catch (error) {
    return NextResponse.json({ error: 'Error al obtener profesores' }, { status: 500 })
  }
}
